### ISSUE TITLE
1.3.1-BACKEND NEGOCIO-Creacion de Microservicio Customer (Clientes)

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre#3]
Se requiere desarrollar el mcs de customer, el cual heredara las dependencias del dominio de negocio y debera implementar las siguientes dependencias:

                 <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>2.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

La entidad debera estar conformada con los siguientes atributos:

id
nombre
celular
apellido
direccionEnvio
email

Este debera implementar las capas de Controlador interfaces y servicios.
Los endpoints necesarios en el controller deben ser los siguientes:

1)_/customer/listarClientes
2)_/customer/buscarId/{id}
3)_/customer/buscarNombre/{nombre}
4)_/customer/buscarApellido/{apellido}
5)__/customer/buscarEmail/{email}
6)__/customer/modificar/{id}
7)_/customer/nuevoCliente
8)_/customer/borrar/{id}

Aplicar la siguiente configuracion en el bootstrap.yml:

```
springdoc:
  swagger-ui:
    path: /swagger/index.html
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: 'true'
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: infraestructuradomain-configserver
      failFast: true
      #name of base properties config file, before profile
      name: config-client
      #profile: development
      label: master
      username: admin
      password: qwerty
      retry:
        max-attempts: 1
        max-interval: 1000
  application:
    name: businessdomain-costumer
server:
  port: '8081'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always

```
Realizar las pruebas  de los diferentes endpoints en el entorno SWAGGER :  http://localhost:8081/swagger-ui/index.htm
