### ISSUE TITLE
1.3.2-BACKEND NEGOCIO-Creacion de Microservicio Product (Producto)

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre#4]
Se requiere desarrollar el mcs de producto, el cual heredara las dependencias del dominio de negocio y debera implementar las siguientes dependencias:

                 <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>2.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

La entidad debera estar conformada con los siguientes atributos:

id
nombre
celular
apellido
direccionEnvio
email

Este debera implementar las capas de Controlador interfaces y servicios.
Los endpoints necesarios en el controller deben ser los siguientes:

1)_/product/listarProductos
2)_/product/obtenerProducto/{id}
3)_/product/modificarProducto/{id}
4)_/product/nuevoProducto
5)_/product/borrarProducto/{id}
6)_/product/actualizarStockProducto
7)_/product/obtenerProducto/tipo/{tipo}
8)_/product/obtenerProducto/nombre/{nombre}
9)_/product/obtenerProducto/especie/{especie}
10)_/product/obtenerProducto/anyProductByName/{nombre}
11)_/product/obtenerStockProducto/{id}

Aplicar la siguiente configuracion en el bootstrap.yml:

```
springdoc:
  swagger-ui:
    path: /swagger/index.html
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: 'true'
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: infraestructuradomain-configserver
      failFast: true
      #name of base properties config file, before profile
      name: config-client
      #profile: development
      label: master
      username: admin
      password: qwerty
      retry:
        max-attempts: 1
        max-interval: 1000
  application:
    name: businessdomain-product
server:
  port: '8083'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always

```
Realizar las pruebas  de los diferentes endpoints en el entorno SWAGGER :  http://localhost:8083/swagger-ui/index.htm
