### ISSUE TITLE
1.3.3-BACKEND NEGOCIO-Creacion de Microservicio Transaction (Transacciones)

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre#5]
Se requiere desarrollar el mcs de transacciones, el cual heredara las dependencias del dominio de negocio y debera implementar las siguientes dependencias:

                 <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>2.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

La entidad debera estar conformada con los siguientes atributos:

Transaction
    id
    referencia
    idCliente
    fechaTransaccion
    monto
    descripcion
    estado;
    canal;
    List<Producttransaction> producttransactions;

Producttransaction . ( Una transaccion puede tener asociados varios productos) Por eso debe ser una relacion de 1 a muchos

     id;
     idProducto;
     cantidadProducto; 
     Transaction transaction;

Este debera implementar las capas de Controlador interfaces y servicios.
Los endpoints necesarios en el controller deben ser los siguientes:

1)_/transaction/listarTransacciones
2)_/transaction/transaccionesCliente/{id}
3)_/transaction/modificarTransaccion/{id}
4)_/transaction/nuevaTransaccion
5)_/transaction/borrarTransaccion/{id}

Aplicar la siguiente configuracion en el bootstrap.yml:

```
springdoc:
  swagger-ui:
    path: /swagger/index.html
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: 'true'
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: infraestructuradomain-configserver
      failFast: true
      #name of base properties config file, before profile
      name: config-client
      #profile: development
      label: master
      username: admin
      password: qwerty
      retry:
        max-attempts: 1
        max-interval: 1000
  application:
    name: businessdomain-transaction
server:
  port: '8082'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always

```
Realizar las pruebas  de los diferentes endpoints en el entorno SWAGGER :  http://localhost:8082/swagger-ui/index.htm
